version: "3"

tasks:
  lint:
    desc: Run linters for DB package (use CI=true for reports)
    cmds:
      - |
        if [[ "{{.CI}}" == "true" ]]; then
          echo "Running DB linters with CI reports..."
          mkdir -p {{.TASKFILE_DIR}}/reports
          uv run ruff check --output-format json --output-file {{.TASKFILE_DIR}}/reports/ruff.json {{.TASKFILE_DIR}}/src {{.TASKFILE_DIR}}/tests
          uv run bandit -c {{.TASKFILE_DIR}}/pyproject.toml -r {{.TASKFILE_DIR}}/src -o {{.TASKFILE_DIR}}/reports/bandit.json --format json
          uv run ty check --output-format github > {{.TASKFILE_DIR}}/reports/gl-code-quality-report.json
        else
          echo "Running DB linters for development..."
          uv run ruff check --fix {{.TASKFILE_DIR}}/src {{.TASKFILE_DIR}}/tests
          uv run bandit -c {{.TASKFILE_DIR}}/pyproject.toml -r {{.TASKFILE_DIR}}/src
          uv run ty check
        fi

  test:
    desc: Run DB package tests (use CI=true for reports)
    cmds:
      - |
        if [[ "{{.CI}}" == "true" ]]; then
          echo "Running DB tests with CI reports..."
          mkdir -p {{.TASKFILE_DIR}}/reports
          uv run pytest {{.TASKFILE_DIR}}/tests \
            --junitxml={{.TASKFILE_DIR}}/reports/junit.xml \
            --cov={{.TASKFILE_DIR}}/src \
            --cov-report=xml:{{.TASKFILE_DIR}}/reports/coverage.xml \
            --cov-report=term-missing
        else
          echo "Running DB tests for development..."
          uv run pytest {{.TASKFILE_DIR}}/tests --cov={{.TASKFILE_DIR}}/src --cov-report=term-missing:skip-covered
        fi
